In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import seaborn as sns

# Importing the data

In [121]:
df = pd.read_csv("drug.csv", header =None, names= ['ID','Age','Gender','Education','Country','Ethnicity','Nscore','Escore','Oscore','Ascore','Cscore','Impulsive','SS',
                                                   'Alcohol','Amphet','Amyl','Benzos','Caff','Cannabis','Choc','Coke','Crack','Ecstasy','Heroin','Ketamine','Legalh','LSD','Meth','Mushrooms','Nicotine','Semer','VSA'])

In [3]:
data = pd.read_csv("drug.csv", header =None, names= ['ID','Age','Gender','Education','Country','Ethnicity','Nscore','Escore','Oscore','Ascore','Cscore','Impulsive','SS',
                                                   'Alcohol','Amphet','Amyl','Benzos','Caff','Cannabis','Choc','Coke','Crack','Ecstasy','Heroin','Ketamine','Legalh','LSD','Meth','Mushrooms','Nicotine','Semer','VSA'])

# Looking at the data

In [5]:
df.head()

ID      Age   Gender  Education  Country  Ethnicity   Nscore   Escore  \
0   1  0.49788  0.48246   -0.05921  0.96082    0.12600  0.31287 -0.57545   
1   2 -0.07854 -0.48246    1.98437  0.96082   -0.31685 -0.67825  1.93886   
2   3  0.49788 -0.48246   -0.05921  0.96082   -0.31685 -0.46725  0.80523   
3   4 -0.95197  0.48246    1.16365  0.96082   -0.31685 -0.14882 -0.80615   
4   5  0.49788  0.48246    1.98437  0.96082   -0.31685  0.73545 -1.63340   

    Oscore   Ascore ...   Ecstasy  Heroin  Ketamine Legalh  LSD Meth  \
0 -0.58331 -0.91699 ...       CL0     CL0       CL0    CL0  CL0  CL0   
1  1.43533  0.76096 ...       CL4     CL0       CL2    CL0  CL2  CL3   
2 -0.84732 -1.62090 ...       CL0     CL0       CL0    CL0  CL0  CL0   
3 -0.01928  0.59042 ...       CL0     CL0       CL2    CL0  CL0  CL0   
4 -0.45174 -0.30172 ...       CL1     CL0       CL0    CL1  CL0  CL0   

  Mushrooms Nicotine Semer  VSA  
0       CL0      CL2   CL0  CL0  
1       CL0      CL4   CL0  CL0  
2       CL1      CL0   CL0  CL0  
3       CL0      CL2   CL0  CL0  
4       CL2      CL2   CL0  CL0  

[5 rows x 32 columns]

We can see that there are 32 columns with first one as ID, next 12 as patient profile information, and rest as drusg usage information

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1885 entries, 0 to 1884
Data columns (total 32 columns):
ID           1885 non-null int64
Age          1885 non-null float64
Gender       1885 non-null float64
Education    1885 non-null float64
Country      1885 non-null float64
Ethnicity    1885 non-null float64
Nscore       1885 non-null float64
Escore       1885 non-null float64
Oscore       1885 non-null float64
Ascore       1885 non-null float64
Cscore       1885 non-null float64
Impulsive    1885 non-null float64
SS           1885 non-null float64
Alcohol      1885 non-null object
Amphet       1885 non-null object
Amyl         1885 non-null object
Benzos       1885 non-null object
Caff         1885 non-null object
Cannabis     1885 non-null object
Choc         1885 non-null object
Coke         1885 non-null object
Crack        1885 non-null object
Ecstasy      1885 non-null object
Heroin       1885 non-null object
Ketamine     1885 non-null object
Legalh       1885 non-null objec

Changing lebels into dummies

In [122]:
for i in range(len(df)):
    for j in range(13,32):
        if df.iloc[i,j] == 'CL0':
            df.iloc[i,j] = 0

In [123]:
for i in range(len(df)):
    for j in range(13,32):
        if df.iloc[i,j] == 'CL1':
            df.iloc[i,j] = 0

In [124]:
for i in range(len(df)):
    for j in range(13,32):
        if df.iloc[i,j] == 'CL2':
            df.iloc[i,j] = 1

In [125]:
for i in range(len(df)):
    for j in range(13,32):
        if df.iloc[i,j] == 'CL3':
            df.iloc[i,j] = 1

In [126]:
for i in range(len(df)):
    for j in range(13,32):
        if df.iloc[i,j] == 'CL4':
            df.iloc[i,j] = 1

In [127]:
for i in range(len(df)):
    for j in range(13,32):
        if df.iloc[i,j] == 'CL5':
            df.iloc[i,j] = 1

In [128]:
for i in range(len(df)):
    for j in range(13,32):
        if df.iloc[i,j] == 'CL6':
            df.iloc[i,j] = 1

In [129]:
df.describe()

ID         Age       Gender    Education      Country  \
count  1885.000000  1885.00000  1885.000000  1885.000000  1885.000000   
mean    945.294960     0.03461    -0.000256    -0.003806     0.355542   
std     545.167641     0.87836     0.482588     0.950078     0.700335   
min       1.000000    -0.95197    -0.482460    -2.435910    -0.570090   
25%     474.000000    -0.95197    -0.482460    -0.611130    -0.570090   
50%     946.000000    -0.07854    -0.482460    -0.059210     0.960820   
75%    1417.000000     0.49788     0.482460     0.454680     0.960820   
max    1888.000000     2.59171     0.482460     1.984370     0.960820   

         Ethnicity       Nscore       Escore       Oscore       Ascore  \
count  1885.000000  1885.000000  1885.000000  1885.000000  1885.000000   
mean     -0.309577     0.000047    -0.000163    -0.000534    -0.000245   
std       0.166226     0.998106     0.997448     0.996229     0.997440   
min      -1.107020    -3.464360    -3.273930    -3.273930    -3.464360   
25%      -0.316850    -0.678250    -0.695090    -0.717270    -0.606330   
50%      -0.316850     0.042570     0.003320    -0.019280    -0.017290   
75%      -0.316850     0.629670     0.637790     0.723300     0.760960   
max       1.907250     3.273930     3.273930     2.901610     3.464360   

          ...           Ecstasy       Heroin     Ketamine       Legalh  \
count     ...       1885.000000  1885.000000  1885.000000  1885.000000   
mean      ...          0.398408     0.112467     0.185676     0.404244   
std       ...          0.489700     0.316024     0.388948     0.490875   
min       ...          0.000000     0.000000     0.000000     0.000000   
25%       ...          0.000000     0.000000     0.000000     0.000000   
50%       ...          0.000000     0.000000     0.000000     0.000000   
75%       ...          1.000000     0.000000     0.000000     1.000000   
max       ...          1.000000     1.000000     1.000000     1.000000   

               LSD         Meth    Mushrooms     Nicotine        Semer  \
count  1885.000000  1885.000000  1885.000000  1885.000000  1885.000000   
mean      0.295491     0.221220     0.368170     0.670557     0.003183   
std       0.456384     0.415179     0.482436     0.470136     0.056343   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     1.000000     0.000000   
75%       1.000000     0.000000     1.000000     1.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               VSA  
count  1885.000000  
mean      0.122016  
std       0.327391  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000  

[8 rows x 32 columns]

Now There is a fictious drug called Semer in this list to find out over claimers. We will remove the over claimers.

In [130]:
list_of_semer_postitive_indexes = df[df['Semer'] != 0 ].index.values

So, who are the people who over claimed?

In [131]:
list_of_semer_postitive_indexes

array([ 727,  817, 1516, 1533, 1698, 1823], dtype=int64)

So, we will remove these people

In [132]:
df_without_semer = df.drop(df.index[[727,  817, 1516, 1533, 1698, 1769, 1806, 1823]])

In [133]:
df_without_semer.shape

(1877, 32)

We can see that 8 people have been removed

In [134]:
df_without_semer['Semer'].value_counts()

0    1877
Name: Semer, dtype: int64

In [135]:
df_final = df.drop(labels='Semer', axis = 1)

So,we can see 8 people who are over claimers have been thrown out

# Seperating the columns

In [112]:
df_profile = df_without_semer.iloc[:,1:13]
df_id = df_without_semer.iloc[:,0:]
df_drug_type = df_without_semer.iloc[:,13:]

# Encoding the profile values

Importing Label Encoder class

In [113]:
from sklearn.preprocessing import LabelEncoder

creating a 'le' object from label encoder class 

In [114]:
le = LabelEncoder()

Applying label encoder to the profiles

In [115]:
df_le = df_profile.apply(lambda x: le.fit_transform(x), axis =0)

Now its time for the drug usage data

Putting the drug usage data into a array to use it in a loop

In [116]:
df_arr = np.array(df_drug_type)

Length of the array

In [117]:
len(df_arr)

1877

Seeing how the array looks like

In [118]:
df_arr

array([[5, 2, 0, ..., 2, 0, 0],
       [5, 2, 2, ..., 4, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 6, 5, ..., 6, 0, 0],
       [5, 0, 0, ..., 4, 0, 0],
       [4, 3, 0, ..., 6, 0, 2]], dtype=int64)

In [119]:
for i in range(0,len(df_arr)):
    for j in range(0,len(df_arr[0])):
        if (df_arr[i][j] == 0):
            df_arr[i][j] = 0
            
        else:
            df_arr[i][j] = 1    

Apply a for loop

Putting the data back to a dataframe

In [36]:
df_drug_type_new = pd.DataFrame(df_arr)

Defining the columns

In [37]:
df.columns

Index(['ID', 'Age', 'Gender', 'Education', 'Country', 'Ethnicity', 'Nscore',
       'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsive', 'SS', 'Alcohol',
       'Amphet', 'Amyl', 'Benzos', 'Caff', 'Cannabis', 'Choc', 'Coke', 'Crack',
       'Ecstasy', 'Heroin', 'Ketamine', 'Legalh', 'LSD', 'Meth', 'Mushrooms',
       'Nicotine', 'Semer', 'VSA'],
      dtype='object')

In [38]:
df_drug_type_new.columns = ['Alcohol',
       'Amphet', 'Amyl', 'Benzos', 'Caff', 'Cannabis', 'Choc', 'Coke', 'Crack',
       'Ecstasy', 'Heroin', 'Ketamine', 'Legalh', 'LSD', 'Meth', 'Mushrooms',
       'Nicotine', 'Semer', 'VSA']

Joining the two encoded data into a single dataframe

In [39]:
df_new = pd.concat([df_le,df_drug_type_new], axis = 1)

There is a problem with concat, it will take the removed values as NaN, so we need to remove them again 

In [40]:
df_new = df_new.drop(df_new.index[[1877,1878,1879,1880,1881,1882,1883,1884]])

Looking at the new dataframe

In [41]:
df_new.tail()

Age  Gender  Education  Country  Ethnicity  Nscore  Escore  Oscore  \
1872  0.0     0.0        4.0      5.0        2.0    16.0    23.0    33.0   
1873  0.0     0.0        2.0      0.0        2.0    31.0    14.0    24.0   
1874  5.0     0.0        4.0      0.0        2.0    43.0    22.0    33.0   
1875  0.0     0.0        4.0      0.0        5.0    23.0    10.0    24.0   
1876  1.0     0.0        4.0      5.0        4.0    22.0    19.0    29.0   

      Ascore  Cscore ...   Ecstasy  Heroin  Ketamine  Legalh  LSD  Meth  \
1872    28.0    12.0 ...       1.0     1.0       1.0     1.0  1.0   1.0   
1873    19.0    21.0 ...       1.0     1.0       1.0     1.0  1.0   1.0   
1874    29.0    19.0 ...       1.0     1.0       1.0     1.0  1.0   1.0   
1875    18.0    23.0 ...       1.0     1.0       1.0     1.0  1.0   1.0   
1876    17.0    18.0 ...       1.0     1.0       1.0     1.0  1.0   1.0   

      Mushrooms  Nicotine  Semer  VSA  
1872        1.0       1.0    1.0  1.0  
1873        1.0       1.0    1.0  1.0  
1874        1.0       1.0    1.0  1.0  
1875        1.0       1.0    1.0  1.0  
1876        1.0       1.0    1.0  1.0  

[5 rows x 31 columns]

In [42]:
df_new.shape

(1877, 31)

But wait ! The ID column is not there, so we need to put there

In [43]:
df_new['ID'] = df_without_semer['ID']

So is it there now?

In [44]:
df_new.head()

Age  Gender  Education  Country  Ethnicity  Nscore  Escore  Oscore  Ascore  \
0  2.0     1.0        5.0      6.0        5.0    27.0    19.0    16.0    17.0   
1  1.0     0.0        8.0      6.0        2.0    17.0    35.0    29.0    28.0   
2  2.0     0.0        5.0      6.0        2.0    19.0    28.0    14.0    12.0   
3  0.0     1.0        7.0      6.0        2.0    22.0    17.0    20.0    27.0   
4  2.0     1.0        8.0      6.0        2.0    31.0    11.0    17.0    21.0   

   Cscore ...   Heroin  Ketamine  Legalh  LSD  Meth  Mushrooms  Nicotine  \
0    24.0 ...      1.0       1.0     1.0  1.0   1.0        1.0       1.0   
1    23.0 ...      1.0       1.0     1.0  1.0   1.0        1.0       1.0   
2    16.0 ...      1.0       1.0     1.0  1.0   1.0        1.0       1.0   
3    28.0 ...      1.0       1.0     1.0  1.0   1.0        1.0       1.0   
4    32.0 ...      1.0       1.0     1.0  1.0   1.0        1.0       1.0   

   Semer  VSA   ID  
0    1.0  1.0  1.0  
1    1.0  1.0  2.0  
2    1.0  1.0  3.0  
3    1.0  1.0  4.0  
4    1.0  1.0  5.0  

[5 rows x 32 columns]

In [45]:
df_new.shape

(1877, 32)

In [46]:
df_new.columns

Index(['Age', 'Gender', 'Education', 'Country', 'Ethnicity', 'Nscore',
       'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsive', 'SS', 'Alcohol',
       'Amphet', 'Amyl', 'Benzos', 'Caff', 'Cannabis', 'Choc', 'Coke', 'Crack',
       'Ecstasy', 'Heroin', 'Ketamine', 'Legalh', 'LSD', 'Meth', 'Mushrooms',
       'Nicotine', 'Semer', 'VSA', 'ID'],
      dtype='object')

In [136]:
df_final = df_new.drop(labels='Semer', axis = 1)

So our final dataframe where no semer positive patient is there

In [138]:
df_final.tail()

Age  Gender  Education  Country  Ethnicity  Nscore  Escore  Oscore  \
1872  0.0     0.0        4.0      5.0        2.0    16.0    23.0    33.0   
1873  0.0     0.0        2.0      0.0        2.0    31.0    14.0    24.0   
1874  5.0     0.0        4.0      0.0        2.0    43.0    22.0    33.0   
1875  0.0     0.0        4.0      0.0        5.0    23.0    10.0    24.0   
1876  1.0     0.0        4.0      5.0        4.0    22.0    19.0    29.0   

      Ascore  Cscore   ...    Ecstasy  Heroin  Ketamine  Legalh  LSD  Meth  \
1872    28.0    12.0   ...        1.0     1.0       1.0     1.0  1.0   1.0   
1873    19.0    21.0   ...        1.0     1.0       1.0     1.0  1.0   1.0   
1874    29.0    19.0   ...        1.0     1.0       1.0     1.0  1.0   1.0   
1875    18.0    23.0   ...        1.0     1.0       1.0     1.0  1.0   1.0   
1876    17.0    18.0   ...        1.0     1.0       1.0     1.0  1.0   1.0   

      Mushrooms  Nicotine  VSA      ID  
1872        1.0       1.0  1.0  1876.0  
1873        1.0       1.0  1.0  1877.0  
1874        1.0       1.0  1.0  1878.0  
1875        1.0       1.0  1.0  1879.0  
1876        1.0       1.0  1.0  1880.0  

[5 rows x 31 columns]

Now the ID column is at the last, we need to put it in the front

In [49]:
cols = df_final.columns.tolist()
cols.insert(0,cols.pop(cols.index('ID')))
df_final = df_final.reindex(columns = cols)

So, this is the dataframe with which we start dong EDA

# EDA

Dividing columns accoring to their category

In [50]:
df_final_demo = df_final.iloc[:,1:6]
df_final_psy_score = df_final.iloc[:,6:11]
df_final_psy = df_final.iloc[:,11:13]
df_final_predictors = df_final.iloc[:,6:13]
df_final_usage = df_final.iloc[:,13:]

Counting values of drug usage column

In [51]:
df_final_usage.apply(pd.Series.value_counts).T

1.0
Alcohol    1877
Amphet     1877
Amyl       1877
Benzos     1877
Caff       1877
Cannabis   1877
Choc       1877
Coke       1877
Crack      1877
Ecstasy    1877
Heroin     1877
Ketamine   1877
Legalh     1877
LSD        1877
Meth       1877
Mushrooms  1877
Nicotine   1877
VSA        1877

In [52]:
df_final.describe()

ID          Age       Gender    Education      Country  \
count  1869.000000  1869.000000  1869.000000  1869.000000  1869.000000   
mean    939.050294     1.355270     0.499732     4.998395     3.833601   
std     542.263389     1.277817     0.500134     1.765569     2.689424   
min       1.000000     0.000000     0.000000     0.000000     0.000000   
25%     470.000000     0.000000     0.000000     4.000000     0.000000   
50%     940.000000     1.000000     0.000000     5.000000     6.000000   
75%    1407.000000     2.000000     1.000000     6.000000     6.000000   
max    1880.000000     5.000000     1.000000     8.000000     6.000000   

         Ethnicity       Nscore       Escore       Oscore       Ascore  \
count  1869.000000  1869.000000  1869.000000  1869.000000  1869.000000   
mean      2.066346    23.913858    22.569288    19.736223    22.886035   
std       0.587054     9.139038     6.736406     6.562456     6.389848   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       2.000000    17.000000    18.000000    15.000000    19.000000   
50%       2.000000    24.000000    23.000000    20.000000    23.000000   
75%       2.000000    30.000000    27.000000    25.000000    27.000000   
max       6.000000    48.000000    41.000000    34.000000    40.000000   

        ...     Crack  Ecstasy  Heroin  Ketamine  Legalh     LSD    Meth  \
count   ...    1877.0   1877.0  1877.0    1877.0  1877.0  1877.0  1877.0   
mean    ...       1.0      1.0     1.0       1.0     1.0     1.0     1.0   
std     ...       0.0      0.0     0.0       0.0     0.0     0.0     0.0   
min     ...       1.0      1.0     1.0       1.0     1.0     1.0     1.0   
25%     ...       1.0      1.0     1.0       1.0     1.0     1.0     1.0   
50%     ...       1.0      1.0     1.0       1.0     1.0     1.0     1.0   
75%     ...       1.0      1.0     1.0       1.0     1.0     1.0     1.0   
max     ...       1.0      1.0     1.0       1.0     1.0     1.0     1.0   

       Mushrooms  Nicotine     VSA  
count     1877.0    1877.0  1877.0  
mean         1.0       1.0     1.0  
std          0.0       0.0     0.0  
min          1.0       1.0     1.0  
25%          1.0       1.0     1.0  
50%          1.0       1.0     1.0  
75%          1.0       1.0     1.0  
max          1.0       1.0     1.0  

[8 rows x 31 columns]

In [53]:
df_final.isnull().sum()

ID           8
Age          8
Gender       8
Education    8
Country      8
Ethnicity    8
Nscore       8
Escore       8
Oscore       8
Ascore       8
Cscore       8
Impulsive    8
SS           8
Alcohol      0
Amphet       0
Amyl         0
Benzos       0
Caff         0
Cannabis     0
Choc         0
Coke         0
Crack        0
Ecstasy      0
Heroin       0
Ketamine     0
Legalh       0
LSD          0
Meth         0
Mushrooms    0
Nicotine     0
VSA          0
dtype: int64

In [54]:
df_final.tail()

ID  Age  Gender  Education  Country  Ethnicity  Nscore  Escore  \
1872  1876.0  0.0     0.0        4.0      5.0        2.0    16.0    23.0   
1873  1877.0  0.0     0.0        2.0      0.0        2.0    31.0    14.0   
1874  1878.0  5.0     0.0        4.0      0.0        2.0    43.0    22.0   
1875  1879.0  0.0     0.0        4.0      0.0        5.0    23.0    10.0   
1876  1880.0  1.0     0.0        4.0      5.0        4.0    22.0    19.0   

      Oscore  Ascore ...   Crack  Ecstasy  Heroin  Ketamine  Legalh  LSD  \
1872    33.0    28.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   
1873    24.0    19.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   
1874    33.0    29.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   
1875    24.0    18.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   
1876    29.0    17.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   

      Meth  Mushrooms  Nicotine  VSA  
1872   1.0        1.0       1.0  1.0  
1873   1.0        1.0       1.0  1.0  
1874   1.0        1.0       1.0  1.0  
1875   1.0        1.0       1.0  1.0  
1876   1.0        1.0       1.0  1.0  

[5 rows x 31 columns]

In [55]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1877 entries, 0 to 1876
Data columns (total 31 columns):
ID           1869 non-null float64
Age          1869 non-null float64
Gender       1869 non-null float64
Education    1869 non-null float64
Country      1869 non-null float64
Ethnicity    1869 non-null float64
Nscore       1869 non-null float64
Escore       1869 non-null float64
Oscore       1869 non-null float64
Ascore       1869 non-null float64
Cscore       1869 non-null float64
Impulsive    1869 non-null float64
SS           1869 non-null float64
Alcohol      1877 non-null float64
Amphet       1877 non-null float64
Amyl         1877 non-null float64
Benzos       1877 non-null float64
Caff         1877 non-null float64
Cannabis     1877 non-null float64
Choc         1877 non-null float64
Coke         1877 non-null float64
Crack        1877 non-null float64
Ecstasy      1877 non-null float64
Heroin       1877 non-null float64
Ketamine     1877 non-null float64
Legalh       1877 

In [56]:
null_columns = df_final.columns[df_final.isnull().any()]

In [57]:
print(df_final[df_final["Age"].isnull()][null_columns])

      ID  Age  Gender  Education  Country  Ethnicity  Nscore  Escore  Oscore  \
727  NaN  NaN     NaN        NaN      NaN        NaN     NaN     NaN     NaN   
817  NaN  NaN     NaN        NaN      NaN        NaN     NaN     NaN     NaN   
1516 NaN  NaN     NaN        NaN      NaN        NaN     NaN     NaN     NaN   
1533 NaN  NaN     NaN        NaN      NaN        NaN     NaN     NaN     NaN   
1698 NaN  NaN     NaN        NaN      NaN        NaN     NaN     NaN     NaN   
1769 NaN  NaN     NaN        NaN      NaN        NaN     NaN     NaN     NaN   
1806 NaN  NaN     NaN        NaN      NaN        NaN     NaN     NaN     NaN   
1823 NaN  NaN     NaN        NaN      NaN        NaN     NaN     NaN     NaN   

      Ascore  Cscore  Impulsive  SS  
727      NaN     NaN        NaN NaN  
817      NaN     NaN        NaN NaN  
1516     NaN     NaN        NaN NaN  
1533     NaN     NaN        NaN NaN  
1698     NaN     NaN        NaN NaN  
1769     NaN     NaN        NaN NaN  
1806     NaN 

In [58]:
df_main = df_final.drop(df_final.index[[727,817,1516,1533,1698,1769,1806,1823]])

In [71]:
df_main.head()

ID  Age  Gender  Education  Country  Ethnicity  Nscore  Escore  Oscore  \
0  1.0  2.0     1.0        5.0      6.0        5.0    27.0    19.0    16.0   
1  2.0  1.0     0.0        8.0      6.0        2.0    17.0    35.0    29.0   
2  3.0  2.0     0.0        5.0      6.0        2.0    19.0    28.0    14.0   
3  4.0  0.0     1.0        7.0      6.0        2.0    22.0    17.0    20.0   
4  5.0  2.0     1.0        8.0      6.0        2.0    31.0    11.0    17.0   

   Ascore ...   Crack  Ecstasy  Heroin  Ketamine  Legalh  LSD  Meth  \
0    17.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   1.0   
1    28.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   1.0   
2    12.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   1.0   
3    27.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   1.0   
4    21.0 ...     1.0      1.0     1.0       1.0     1.0  1.0   1.0   

   Mushrooms  Nicotine  VSA  
0        1.0       1.0  1.0  
1        1.0       1.0  1.0  
2        1.0       1.0  1.0  
3        1.0       1.0  1.0  
4        1.0       1.0  1.0  

[5 rows x 31 columns]

In [ ]:
age_plot = sns.countplot(df_main['Age'])

In [ ]:
education_plot = sns.countplot(df_main['Education'])

In [ ]:
country_plot = sns.countplot(df_main['Country'])

In [ ]:
ethnicity_plot = sns.countplot(df_main['Ethnicity'])

In [ ]:
Nscore_plot = sns.countplot(df_main['Nscore'])

In [ ]:
Escore_plot = sns.countplot(df_main['Escore'])

In [ ]:
Oscore_plot = sns.countplot(df_main['Oscore'])

In [ ]:
Ascore_plot = sns.countplot(df_main['Ascore'])

In [ ]:
Cscore_plot = sns.countplot(df_main['Cscore'])

In [ ]:
Impulsive_plot = sns.countplot(df_main['Impulsive'])

In [ ]:
SS_plot = sns.countplot(df_main['SS'])

# Splitting the data for training and testing

In [73]:
df_final.columns

Index(['ID', 'Age', 'Gender', 'Education', 'Country', 'Ethnicity', 'Nscore',
       'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsive', 'SS', 'Alcohol',
       'Amphet', 'Amyl', 'Benzos', 'Caff', 'Cannabis', 'Choc', 'Coke', 'Crack',
       'Ecstasy', 'Heroin', 'Ketamine', 'Legalh', 'LSD', 'Meth', 'Mushrooms',
       'Nicotine', 'VSA'],
      dtype='object')

In [74]:
df_final_pre = df_final.loc[:,['Age','Education', 'Nscore',
       'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsive', 'SS']]

In [120]:
df_final.tail()

ID      Age   Gender  Education  Country  Ethnicity   Nscore   Escore  \
1880  1884 -0.95197  0.48246   -0.61113 -0.57009   -0.31685 -1.19430  1.74091   
1881  1885 -0.95197 -0.48246   -0.61113 -0.57009   -0.31685 -0.24649  1.74091   
1882  1886 -0.07854  0.48246    0.45468 -0.57009   -0.31685  1.13281 -1.37639   
1883  1887 -0.95197  0.48246   -0.61113 -0.57009   -0.31685  0.91093 -1.92173   
1884  1888 -0.95197 -0.48246   -0.61113  0.21128   -0.31685 -0.46725  2.12700   

       Oscore   Ascore ...   Crack  Ecstasy  Heroin  Ketamine  Legalh  LSD  \
1880  1.88511  0.76096 ...       0        0       0         0       3    3   
1881  0.58331  0.76096 ...       0        2       0         0       3    5   
1882 -1.27553 -1.77200 ...       0        4       0         2       0    2   
1883  0.29338 -1.62090 ...       0        3       0         0       3    3   
1884  1.65653  1.11406 ...       0        3       0         0       3    3   

      Meth  Mushrooms  Nicotine  VSA  
1880     0          0         0    5  
1881     4          4         5    0  
1882     0          2         6    0  
1883     0          3         4    0  
1884     0          3         6    2  

[5 rows x 31 columns]

In [94]:
df_final_usage_count = df_final_usage.astype(int) 
x = df_final_pre.values
y = df_final_usage_count.loc[:,'Cannabis'].values

As we are trying to predict for different drugs we can change the drug name here. I have taken "Cannabis" here. 

In [63]:
from sklearn.model_selection import train_test_split

Splitting the dataset

In [95]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

For prediction we have to change the values into integer for the model to work

In [96]:
x_train = x_train.astype(int)
y_train = y_train.astype(int)
x_test = x_test.astype(int)
y_test = y_test.astype(int)

In [82]:
x_train

array([[ 0,  6, 26, ..., 11,  4,  5],
       [ 0,  1, 41, ..., 11,  6,  8],
       [ 2,  5, 19, ..., 19,  6,  5],
       ...,
       [ 0,  6, 40, ..., 25,  1,  7],
       [ 0,  6, 34, ..., 27,  2,  4],
       [ 0,  4, 39, ..., 17,  6,  9]])

In [83]:
y_train

array([1, 1, 1, ..., 1, 1, 1])

In [84]:
x_test

array([[ 1,  7, 35, ..., 30,  3,  6],
       [ 3,  1, 20, ..., 28,  3,  5],
       [ 2,  5, 36, ..., 11,  8,  8],
       ...,
       [ 3,  1, 37, ..., 23,  6,  7],
       [ 0,  0, 13, ..., 20,  6,  9],
       [ 1,  8, 29, ..., 27,  1,  7]])

In [85]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

# Decision Tree

In [78]:
from sklearn.tree import DecisionTreeClassifier

In [97]:
classifier = DecisionTreeClassifier(criterion='entropy', random_state= 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [98]:
y_pred_dt = classifier.predict(x_test)

In [99]:
con_matrix_dt = confusion_matrix(y_test, y_pred_dt)
con_matrix_dt

array([[470]], dtype=int64)

In [100]:
acc_score_dt = accuracy_score(y_test, y_pred_dt)
acc_score_dt

1.0

# Random Forest

In [89]:
from sklearn.ensemble import RandomForestClassifier 

In [90]:
rfc = RandomForestClassifier(criterion = 'entropy', n_estimators = 31, random_state= 0)

In [91]:
rfc.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=31, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [92]:
y_pred_rfc = rfc.predict(x_test)

In [93]:
con_matrix_rfc = confusion_matrix(y_test, y_pred_rfc)
con_matrix_rfc

array([[470]], dtype=int64)

In [103]:
acc_score_rfc = accuracy_score(y_test, y_pred_rfc)
acc_score_rfc

1.0

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn =KNeighborsClassifier(metric ='minkowski', n_neighbors = 18, weights = 'distance')

In [ ]:
knn.fit(x_train, y_train)

In [ ]:
y_pred_knn = knn.predict(x_test)

In [ ]:
con_matrix_knn = confusion_matrix(y_test, y_pred_knn)
con_matrix_knn

In [ ]:
acc_score_knn = accuracy_score(y_test, y_pred_knn)
acc_score_knn

Plotting accuracy scores vs the number of neighbors in KNN

In [ ]:
k_range = range(1,31)

In [ ]:
acc_sc =[]
for i in k_range:
    knnclass =KNeighborsClassifier(n_neighbors= i, metric ='minkowski')
    knnclass.fit(x_train, y_train)
    y_pred_knn = knnclass.predict(x_test)
    acc = accuracy_score(y_test, y_pred_knn)
    acc_sc.append(acc)

In [ ]:
acc_sc_df = pd.DataFrame(acc_sc)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
acc_sc_df.plot(kind='bar', figsize = (10,10))
plt.xlabel('Value of K for KNN')
plt.ylabel('Cross-Validated Accuracy')

We can see best value comes for n = 19

# Multi Label KNN

In [ ]:
from skmultilearn.adapt import MLkNN

In [ ]:
ml_knn = MLkNN(k=20)

In [ ]:
x_mlknn = df_final_predictors.values
y_mlknn = df_final_usage_count.loc[:,:].values

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_mlknn, y_mlknn, test_size=0.25, random_state=0)

In [ ]:
x_train_mlknn = x_train.astype(int)
y_train_mlknn = y_train.astype(int)
x_test_mlknn = x_test.astype(int)
y_test_mlknn = y_test.astype(int)

In [ ]:
ml_knn.fit(x_train_mlknn, y_train_mlknn)

In [ ]:
y_pred_mlknn = ml_knn.predict(x_test_mlknn)

In [ ]:
acc_score_mlknn = accuracy_score(y_test_mlknn, y_pred_mlknn)
acc_score_mlknn

In [ ]:
k_range = range(1,51)

In [ ]:
acc_sc_mlknn =[]
for i in k_range:
    mlknn_class =MLkNN(k= i)
    mlknn_class.fit(x_train_mlknn, y_train_mlknn)
    y_pred_mlknn = mlknn_class.predict(x_test_mlknn)
    acc = accuracy_score(y_test_mlknn, y_pred_mlknn)
    acc_sc_mlknn.append(acc)

In [ ]:
acc_sc_mlknn_df = pd.DataFrame(acc_sc_mlknn)

In [ ]:
acc_sc_mlknn_df.plot(kind='bar', figsize = (10,10))
plt.xlabel('Value of K for MLkNN')
plt.ylabel('Accuracy Score')

# k fold cross validation for KNN on only one drug

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
accu_knn = cross_val_score(estimator= knn, X = x_train, y = y_train, cv= 10, scoring= 'accuracy')

In [ ]:
accu_knn.mean()

# K fold Corss validation for random forest on only one drug

In [ ]:
accu_rf = cross_val_score(estimator= rfc, X = x_train, y = y_train, cv= 10, scoring= 'accuracy')

In [ ]:
accu_rf.mean()

# Gridsearch CV for KNN for a single drug

In [ ]:
from sklearn.model_selection import GridSearchCV

parameters to be defined for KNN

In [ ]:
knn.get_params().keys()

The options for different parameters

In [ ]:
knn_neigh = list(range(1,51))
weight_options = ['uniform', 'distance']
metric_options = ['minkowski','euclidean']

In [ ]:
parameters_knn = dict(metric = metric_options,n_neighbors = knn_neigh, weights = weight_options)

Defining grid search

In [ ]:
grid_knn = GridSearchCV(estimator = knn,param_grid = parameters_knn, cv=10, scoring='accuracy')

Applying grid search

In [ ]:
grid_knn.fit(x_train, y_train)

Best Score and parameter for KNN

In [ ]:
print(grid_knn.best_score_)
print(grid_knn.best_params_)

# Searching for best parameters for each of the drugs based on KNN

In [ ]:
cols = df_final_usage_count.columns
grid_best_scores =[]
grid_best_param = []

for i in range(len(cols)):
    x_loop = df_final_predictors.values
    y_loop = df_final_usage_count.iloc[:,i].values
    x_train, x_test, y_train, y_test = train_test_split(x_loop, y_loop, test_size=0.25, random_state=0)
    x_train = x_train.astype(int)
    y_train = y_train.astype(int)
    x_test = x_test.astype(int)
    y_test = y_test.astype(int)
    knn_neigh = list(range(1,51))
    weight_options = ['uniform', 'distance']
    metric_options = ['minkowski','euclidean']
    parameters_knn = dict(metric = metric_options,n_neighbors = knn_neigh, weights = weight_options)
    grid_knn = GridSearchCV(estimator = knn,param_grid = parameters_knn, cv=10, scoring='accuracy')
    grid_knn.fit(x_train, y_train)
    grid_best_scores.append(grid_knn.best_score_)
    grid_best_param.append(grid_knn.best_params_)

In [ ]:
grid_best_param_knn = pd.DataFrame(grid_best_param)
grid_best_param_knn

In [ ]:
grid_best_param_knn["metric"] = grid_best_param_knn.metric.astype(str)
grid_best_param_knn["weights"] = grid_best_param_knn.weights.astype(str)

# GridsearchCV for random forest for a single drug

Parameters for random forest

In [ ]:
rfc.get_params().keys()

In [ ]:
criterion_rfc = ['gini','entropy']
n_estimators_rfc = list(range(1,101))

In [ ]:
parameters_rfc = dict(criterion = criterion_rfc, n_estimators = n_estimators_rfc)

In [ ]:
grid_rfc = GridSearchCV(estimator = rfc,param_grid = parameters_rfc, cv=10, scoring='accuracy')

In [ ]:
grid_rfc.fit(x_train, y_train)

In [ ]:
print(grid_rfc.best_score_)
print(grid_rfc.best_params_)

# Searching for best parameters for each of the drug based on Decision Tree

In [ ]:
cols = df_final_usage_count.columns
grid_best_scores_dt =[]
grid_best_param_dt = []

for i in range(len(cols)):
    x_loop = df_final_predictors.values
    y_loop = df_final_usage_count.iloc[:,i].values
    x_train, x_test, y_train, y_test = train_test_split(x_loop, y_loop, test_size=0.25, random_state=0)
    x_train = x_train.astype(int)
    y_train = y_train.astype(int)
    x_test = x_test.astype(int)
    y_test = y_test.astype(int)
    criterion_rfc = ['gini','entropy']
    n_estimators_rfc = list(range(1,101))
    parameters_rfc = dict(criterion = criterion_rfc, n_estimators = n_estimators_rfc)
    grid_rfc = GridSearchCV(estimator = rfc,param_grid = parameters_rfc, cv=10, scoring='accuracy')
    grid_rfc.fit(x_train, y_train)
    grid_best_scores_dt.append(grid_rfc.best_score_)
    grid_best_param_dt.append(grid_rfc.best_params_)

In [ ]:
grid_best_param_dt_df = pd.DataFrame(grid_best_param_dt)
grid_best_param_dt_df

# Now all these have been done for only one drug. Let us now apply these for all the drugs based on KNN

In [ ]:
df_final.columns

In [ ]:
cols = df_final_usage_count.columns

In [ ]:
acc_score_cols = []
for i in range(len(cols)):
    x_loop = df_final_predictors.values
    y_loop = df_final_usage_count.iloc[:,i].values
    x_train, x_test, y_train, y_test = train_test_split(x_loop, y_loop, test_size=0.25, random_state=0)
    x_train = x_train.astype(int)
    y_train = y_train.astype(int)
    x_test = x_test.astype(int)
    y_test = y_test.astype(int)
    knn_df = KNeighborsClassifier(metric =grid_best_param_knn.loc[i,'metric'], n_neighbors = grid_best_param_knn.loc[i,'n_neighbors'], weights = grid_best_param_knn.loc[i,'weights'])
    knn_df.fit(x_train, y_train)
    y_pred_knn = knn_df.predict(x_test)
    acc_score_knn = accuracy_score(y_test, y_pred_knn)
    acc_score_cols.append(acc_score_knn)

In [ ]:
acc_score_df = pd.DataFrame(acc_score_cols)
acc_score_df = acc_score_df.T

In [ ]:
acc_score_df.columns =['Alcohol',
       'Amphet', 'Amyl', 'Benzos', 'Caff', 'Cannabis', 'Choc', 'Coke', 'Crack',
       'Ecstasy', 'Heroin', 'Ketamine', 'Legalh', 'LSD', 'Meth', 'Mushrooms',
       'Nicotine', 'VSA']

In [ ]:
acc_score_df

In [ ]:
import seaborn as sn

In [ ]:
from matplotlib import pyplot
fig, ax = pyplot.subplots(figsize=(13,13))
sn.barplot(x=acc_score_df.columns,y=acc_score_df.iloc[0,:], ax=ax)

# Now all these have been done for only one drug. Let us now apply these for all the drugs based on Random Forest

In [ ]:
acc_score_cols_rf = []
for i in range(len(cols)):
    x_loop = df_final_predictors.values
    y_loop = df_final_usage_count.iloc[:,i].values
    x_train, x_test, y_train, y_test = train_test_split(x_loop, y_loop, test_size=0.25, random_state=0)
    x_train = x_train.astype(int)
    y_train = y_train.astype(int)
    x_test = x_test.astype(int)
    y_test = y_test.astype(int)
    rfc_df = RandomForestClassifier(criterion = grid_best_param_dt_df.loc[i,'criterion'], n_estimators = grid_best_param_dt_df.loc[i,'n_estimators'], random_state= 0)
    rfc_df.fit(x_train, y_train)
    y_pred_rfc = rfc_df.predict(x_test)
    acc_score_rfc = accuracy_score(y_test, y_pred_rfc)
    acc_score_cols_rf.append(acc_score_rfc)

In [ ]:
acc_score_df_rf = pd.DataFrame(acc_score_cols_rf)
acc_score_df_rf = acc_score_df_rf.T

In [ ]:
acc_score_df_rf.columns =['Alcohol',
       'Amphet', 'Amyl', 'Benzos', 'Caff', 'Cannabis', 'Choc', 'Coke', 'Crack',
       'Ecstasy', 'Heroin', 'Ketamine', 'Legalh', 'LSD', 'Meth', 'Mushrooms',
       'Nicotine', 'VSA']

In [ ]:
acc_score_df_rf

In [ ]:
acc_score_df

In [ ]:
fig, ax = pyplot.subplots(figsize=(13,13))
sn.barplot(x=acc_score_df_rf.columns,y=acc_score_df_rf.iloc[0,:], ax=ax)